services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost:5001
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
    depends_on:
      - redis
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5001:5001
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    depends_on: 
      - backend

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped

  db:
    container_name: db_backend
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres

    