services:
  express-app:
    build: ./express-app

  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    environment: 
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock